name: Update event
on:
  repository_dispatch:
    types: [update_event]

jobs:
  build:
    runs-on: ubuntu-latest
    name: React on dispatched event
    steps:
      - uses: hmarr/debug-action@v2
      - run: echo ${{ github.event }}
