name: Update event
on:
  repository_dispatch:
    types: [update_event]

jobs:
  build:
    runs-on: ubuntu-latest
    name: React on dispatched event
    steps:
      - name: generate name of branch
        id: branch
        uses: frabert/replace-string-action@v2.0
        with:
          pattern: '(\d+\.\d+)\.\d+'
          string: "${{ github.event.client_payload.ref }}"
          replace-with: '$1.x'
      - name: checkout branch
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.branch.outputs.replaced }}
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "${{ steps.branch.outputs.replaced }}-dev"
          replace: ${{ github.event.client_payload.ref }}
          regex: false
      - name: Commit and push the changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          tagging_message: ${{ github.event.client_payload.ref }}
          commit_message: Release ${{ github.event.client_payload.ref }}
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: ${{ github.event.client_payload.ref }}
          replace: "${{ steps.branch.outputs.replaced }}-dev"
          regex: false
      - name: Commit and push the changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Back to dev
