name: Update event
on:
  repository_dispatch:
    types: [update_event]

jobs:
  build:
    runs-on: ubuntu-latest
    name: React on dispatched event
    steps:
      - name: generate name of branch
        id: branch
        uses: frabert/replace-string-action@v2.0
        with:
          pattern: '(\d+\.\d+)\.\d+'
          string: "${{ github.event.client_payload.ref }}"
          replace-with: '$1.x'
      - uses: actions/checkout@v3
      - name: Checkout branch
        run: git checkout -B ${{ steps.branch.outputs.replaced }}
